name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on pushing to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # SSH private key as GitHub Secret

      # Install dependencies (Node.js, npm)
      - name: Install Dependencies
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
          source ~/.bashrc
          nvm install node
          nvm use node
          npm install

      # Deploy to EC2 instance
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} "cd /path/to/your/app && git pull origin main && npm install && pm2 restart app.js"

