name: Deploy to EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the dev branch
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH agent for EC2 access
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      # Step 3: List repository files for debugging (optional)
      - name: List repository files
        run: |
          ls -R

      # Step 4: Check if 'myapp_old' exists and delete it if found
      - name: Check and delete myapp_old folder if exists
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.51.178.128 "if [ -d '/var/www/myapp_old' ]; then sudo rm -rf /var/www/myapp_old; fi"

      # Step 5: Move 'myapp' folder to 'myapp_old' folder
      - name: Move myapp to myapp_old
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.51.178.128 "if [ -d '/var/www/myapp' ]; then sudo mv /var/www/myapp /var/www/myapp_old; fi"

      # Step 6: Create new 'myapp' folder
      - name: Create new myapp folder
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.51.178.128 "sudo mkdir -p /var/www/myapp && sudo chown -R ubuntu:ubuntu /var/www/myapp"

      # Step 7: Clone the repository into the 'myapp' folder
      - name: Clone repository into myapp folder
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.51.178.128 "cd /var/www/myapp && git clone https://github.com/sumit-h-nagarkoti/tamma.git"

      # Step 8: Install dependencies and PM2
      - name: Install dependencies and PM2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.51.178.128 "cd /var/www/myapp/tamma && npm install -g pm2 && npm install"

      # Step 9: Stop the PM2 app if running
      - name: Stop the app using PM2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.51.178.128 "cd /var/www/myapp/tamma && pm2 stop my-app || true"

      # Step 10: Start the app with PM2
      - name: Start the app using PM2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.51.178.128 "cd /var/www/myapp/tamma && pm2 start app.js --name 'my-app' --env production"
