name: Deploy Node.js Application to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on push to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the Ubuntu runner

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH and deploy to EC2
      - name: Set up SSH and deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update system packages on EC2 instance
            sudo apt update && sudo apt upgrade -y

            # Install Node.js (via NVM)
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
            source ~/.bashrc
            nvm install node
            nvm use node

            # Confirm Node.js and npm installation
            node -v
            npm -v

            # Install Git and PM2
            sudo apt install git -y
            npm install pm2 -g

            # Clone or pull the latest changes from the repository
            if [ ! -d "/home/${{ secrets.EC2_USER }}/tamma" ]; then
              git clone https://github.com/sumit-h-nagarkoti/tamma.git /home/${{ secrets.EC2_USER }}/tamma
            else
              cd /home/${{ secrets.EC2_USER }}/tamma && git pull origin main
            fi

            # Navigate to the project directory (the 'tamma' directory)
            cd /home/${{ secrets.EC2_USER }}/tamma

            # Install dependencies
            npm install

            # Start the application with PM2
            pm2 start app.js --name "tamma-app"

            # Ensure the app is running (Optional: for health check)
            curl --silent --fail http://0.0.0.0:3000/ || exit 1

            # Save the PM2 process list and setup for auto-start
            pm2 save
            pm2 startup
