name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the dev branch
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH agent for EC2 access
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      # Step 3: List repository files for debugging (optional)
      - name: List repository files
        run: |
          ls -R

      # Step 4: Check and delete myapp_old folder if exists
      - name: Check and delete myapp_old folder if exists
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_Public_IP }} "if [ -d '/var/www/myapp_old' ]; then sudo rm -rf /var/www/myapp_old; fi"

      # Step 5: Move myapp to myapp_old
      - name: Move myapp to myapp_old
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_Public_IP }} "if [ -d '/var/www/myapp' ]; then sudo mv /var/www/myapp /var/www/myapp_old; fi"

      # Step 6: Create new myapp folder
      - name: Create new myapp folder
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_Public_IP }} "sudo mkdir -p /var/www/myapp && sudo chown -R ubuntu:ubuntu /var/www/myapp"

      # Step 7: Clone the repository into the 'myapp' folder
      - name: Clone repository into myapp folder
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_Public_IP }} "cd /var/www/myapp && git clone https://github.com/sumit-h-nagarkoti/tamma.git"

      # Step 8: Install Node.js and PM2
      - name: Install Node.js and PM2 
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_Public_IP }} "cd /var/www/myapp/tamma && npm install pm2 --save && npm install"

      # Step 9: Copy the .env file from S3 to EC2
      - name: Copy .env file from S3 to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_Public_IP }} "aws s3 cp s3://github-s3bucket/.env /var/www/myapp/tamma/.env"

      # Step 10: Stop the app using PM2
      - name: Stop the app using PM2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_Public_IP }} "cd /var/www/myapp/tamma && npx pm2 stop my-app || true"

      # Step 11: Start the app with PM2 (local)
      - name: Start the app using PM2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_Public_IP }} "cd /var/www/myapp/tamma && npx pm2 start app.js --name 'my-app' --env production"
