name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on pushing to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up SSH agent
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      # Install Node.js and dependencies
      - name: Install Node.js and dependencies
        run: |
          # Install NVM
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash

          # Load nvm
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

          # Install Node.js using nvm
          nvm install node
          nvm use node

          # Navigate to the correct directory where app.js is located
          cd tamma || exit  # Ensure you are in the correct directory (replace 'tamma' if needed)

          # Install npm dependencies
          npm install

      # Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_SSH_USER }}@${{ secrets.EC2_IP }} << 'EOF'
            # Load nvm on EC2
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

            # Navigate to the app directory on EC2
            cd /home/ubuntu/tamma || exit  # Adjust this path based on where your app is located on EC2
            git pull origin main || exit  # Pull latest changes from GitHub
            npm install || exit  # Install dependencies
            pm2 restart myapp || pm2 start app.js --name "myapp"  # Restart app using PM2
          EOF
